logging:
  level:
    org.zalando.logbook: TRACE
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:./db/filmorate;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: password